sudo: false
language: node_js
node_js:
- '4'
- '6'
- '8'
- '10'
matrix:
  fast_finish: true
  allow_failures:
  - node_js: '10'
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/node-publish.bash)"
notifications:
  slack:
    secure: jmtIEliTK6x1Sry++o6ZJl82h+xGruMMps/5GOIeNY+7Rh47eTFqWvt/I3sMr8bL2RvlyeFdhjkZJkoWys0RIg1DZis55DHv140EBbKl2eS5n/L4nYvZZ8r4FdEFYko4Uj5CNuqsmi5CIxq3GOcqpH8ZuFf/5dx+gRZFXsKaqJM=
  email:
    recipients:
      secure: QUX1ORXZkCHbCdCm3gBIzO7ygZttDjaEA5nSsOUCukC2uHhsOuZ7kelK3Vs4lHWxQ5EiHiMFqJu5Ulmob8cUYTPSdC/3kzfLGNTgTQ16hwSzGEJUQiJTI8rIwTEVzWkrACLu1XKrfWc62W3ajbb4nd3bbAuHWuZOq/YW28t6Ros=
